# Generated by Django 3.0 on 2019-12-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='Concatenation of the sighting session day and month.'),
        ),
    ]
